Update Github Actions config

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -1,6 +1,6 @@
 name: Verkle Gas Benchmark
 run-name: ${{ github.actor }} Verkle Gas Benchmark 🚀
-on: [push]
+on: [ push ]
 jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-latest
@@ -21,10 +21,40 @@ jobs:
       - name: Run install
         uses: borales/actions-yarn@v4
         with:
-           cmd: install
+          cmd: install
+
+      - name: Hardhat Compile
+        run: |
+          yarn compile
+
+      - name: Run Lint and
+        run: |
+          yarn lint
 
       - name: Run Lint and TypeScript checks
         run: |
-          yarn preprocess
+          yarn tsc
+
+      - name: Spin up Hardhat Node
+        uses: miguelteixeiraa/action-run-in-background@v1
+        with:
+          script: |
+            # run some blocking stuff
+            hardhat-node
+          readiness-script: |
+            # check if whatever is it to run, is ready
+            if curl -sSf http://localhost:8545/ > /dev/null; then
+                echo "curl request was successful."
+            else
+                echo "curl request failed."
+                exit 1
+            fi
+          shell: bash
+          timeout: 30
+
+      - name: Generate HandleOps Transactions
+        run: |
+          yarn test
+
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
